Activities integration
MetaProvide/adminly_clients pull request #11
Opened 2022-05-16 15:14 UTC by oliveiraigorm

2022-05-16 17:24 UTC, oliveiraigorm commented
@mwalbeck Did a lot of debugging and looking at examples but couldn't get the activity posted, could you latter take a look on what might be missing? Thanks!

2022-05-16 19:40 UTC, mwalbeck commented
Okay, so I have taken a look, and from what I can see I think you're missing a Provider. So there are 3 components, the filter, the provider and the settings. The provider is for displaying the actual activity. I can at least see in the database that the activity is actually being created. Here is an example from the dav app, which is the calendar backend https://github.com/nextcloud/server/blob/master/apps/dav/lib/CalDAV/Activity/Provider/Calendar.php

The provider also needs to be registered in the info.xml.

It seems the common approach is to use a more computer friendly string for the subject of the event and then use that to figure out the type of event and then in the provider put together a human-readable string to present in the activity app.

2022-05-16 19:40 UTC, mwalbeck commented on lib/Controller/PageController.php
> +					"New Client added",
The subject could be changed to something like client_added and then in the provider file that is turned into something more human-readable to present to the user.

2022-05-17 09:13 UTC, oliveiraigorm commented
> Okay, so I have taken a look, and from what I can see I think you're missing a Provider. So there are 3 components, the filter, the provider and the settings. The provider is for displaying the actual activity. I can at least see in the database that the activity is actually being created. Here is an example from the dav app, which is the calendar backend https://github.com/nextcloud/server/blob/master/apps/dav/lib/CalDAV/Activity/Provider/Calendar.php
> 
> The provider also needs to be registered in the info.xml.
> 
> It seems the common approach is to use a more computer friendly string for the subject of the event and then use that to figure out the type of event and then in the provider put together a human-readable string to present in the activity app.

Thanks! I was thinking the Provider was necessary for more complex rendering and not mandatory, my mistake.

2022-05-17 11:20 UTC, oliveiraigorm commented on lib/Controller/PageController.php
> +					"New Client added",
Managed to get it almost there, I'm able to display it but need to do some fixes to make the client name bold.

![image](https://user-images.githubusercontent.com/29747887/168799383-d65bca45-f13b-4ecb-9e94-7f0e9799db06.png)

2022-05-18 11:13 UTC, oliveiraigorm commented
@mwalbeck 

Currently I'm able to show the activities like this:

![image](https://user-images.githubusercontent.com/29747887/169023244-3fa659a9-7d6d-4263-85d4-c10fecba60a0.png)

To the the client name shown in bold there's a need to set the RichSubject of the event by sending the parameter(s) (the client object in this case). I've tried to set it in multiple ways, following the files and comments activities, but with no success.  

![image](https://user-images.githubusercontent.com/29747887/169023156-99be099f-582d-42d6-9c8c-391df88d771d.png)

Doing a lot of debugging I found out that this error is thrown. I've tried to add a client entry to Definitions.php but that didn't solve it either. 

![image](https://user-images.githubusercontent.com/29747887/169023026-fbc8d548-bbce-4be4-94f4-ea6a2edaacf4.png)

2022-05-18 11:15 UTC, mwalbeck commented
@oliveiraigorm Very nice job so far, I'll take a look and see if I can make it behave

2022-05-19 10:41 UTC, mwalbeck requested changes

2022-05-19 10:41 UTC, mwalbeck commented on lib/Controller/PageController.php
>  			return $e->getMessage();
This should probably be changed to `throw $e;`

2022-05-19 10:41 UTC, mwalbeck commented on lib/Controller/PageController.php
>  			$this->mapper->insert($client);
We could store the return value in a variable called $new_client and then return that at the end for a more useful return value. That will also follow conventions more.

2022-05-19 10:41 UTC, mwalbeck commented on lib/Controller/PageController.php
>  			return "Success";
return $new_client;

2022-05-19 10:41 UTC, mwalbeck commented on lib/Activity/Provider.php
> +		$subjectParameters = $event->getSubjectParameters();
We should move this one below the if statement, so we don't actually store the parameters unless it's an event we're going to process.

2022-05-19 10:41 UTC, mwalbeck commented on lib/Activity/Provider.php
> +	protected $eventMerger;
For now the eventMerger isn't being used, so let's remove it.

2022-05-19 10:41 UTC, mwalbeck commented on lib/Activity/Provider.php
> +	 * @param IGroupManager $groupManager
GroupManager also isn't being used so let's remove the comment.

2022-05-19 15:43 UTC, mwalbeck commented on lib/Controller/PageController.php
>  			$this->mapper->insert($client);
Oh, I meant something slightly different. If change all the $new_client variables back to $client and then just change line 84 to

```
$new_client = $this->mapper->insert($client);
```

And then keep the `return $new_client` on line 104

2022-05-19 21:05 UTC, mwalbeck approved these changes

2022-05-19 21:06 UTC, merged