create client functionality
MetaProvide/adminly_clients pull request #3
Opened 2022-04-20 16:31 UTC by oliveiraigorm

2022-04-20 18:25 UTC, mwalbeck requested changes

2022-04-20 18:25 UTC, mwalbeck commented on lib/Controller/PageController.php
> +		return (string) $this->mapper->create($client);
Why is the return value being type casted to a string?

2022-04-20 18:25 UTC, mwalbeck commented on lib/Db/ClientMapper.php
> +	public function create(Client $client) {
We actually get a "create" function for free with Nextcloud called `insert`, so I think we should use that instead of defining our own. Unless of course there is a good reason for it, but then I would suggest changing the name of the function to `insert` to keep it consistent.

2022-04-21 12:01 UTC, oliveiraigorm commented on lib/Controller/PageController.php
> +		return (string) $this->mapper->create($client);
Was to cast the int returned when it was successful, but that was far from a good solution. I've changed it to return a clear "Success" message

2022-04-21 13:52 UTC, mwalbeck commented on lib/Controller/PageController.php
> +			return "Success";
I think we can handle the return values in a better way, but until we have a better idea of the UX I don't want to spend too much time on something we're most likely going to change anyway.

2022-04-21 13:52 UTC, mwalbeck approved these changes

2022-04-21 13:52 UTC, merged

2022-04-21 13:54 UTC, oliveiraigorm commented on lib/Controller/PageController.php
> +			return "Success";
Yep, for now it's a quick way to find out if there was some error when inserting into the database