Next & Last sessions
MetaProvide/adminly_clients pull request #34
Opened 2022-07-04 10:36 UTC by oliveiraigorm

2022-07-12 10:37 UTC, oliveiraigorm commented on lib/Controller/PageController.php
> +
Did you mean shouldn't? 
Should it be like this then?
![image](https://user-images.githubusercontent.com/29747887/178471543-632768d6-167b-447b-9a39-20c2944cd4c7.png)

2022-07-12 10:42 UTC, mwalbeck commented on lib/Controller/PageController.php
> +
Ahh yeah, sorry about that ...

Yes, there shouldn't be an empty line

2022-07-12 14:15 UTC, frozenbanana requested changes
Check it out and talk to me if it makes sense.

2022-07-12 14:15 UTC, frozenbanana commented on lib/Controller/PageController.php
> +		$sixWeeksAgo = $sixWeeksAgo->modify("-6 week");
Why is this needed?

2022-07-12 14:15 UTC, frozenbanana commented on lib/Controller/PageController.php
> +		$sixWeeksAgo = $sixWeeksAgo->modify("-6 week");
Or more precisely. Are we using the magic time distance of 6 week back in time to find last session?

So if the last session was 6 weeks and one day ago there was no last session?

2022-07-12 14:15 UTC, frozenbanana commented on lib/Controller/PageController.php
> +		$sixWeeksAgo = $sixWeeksAgo->modify("-6 week");
```suggestion
		$userStartTime = $this->getTimeUserCreated($this->userId);
```

2022-07-12 14:15 UTC, frozenbanana commented on src/components/Table.vue
> +			if (date) return dayjs(date).format("DD/MM hh:mm");
We should think about locales and format our dates and times accordingly. @mwalbeck A topic to bring up on tech checkin meeting.

2022-07-12 14:30 UTC, oliveiraigorm commented on src/components/Table.vue
> +			if (date) return dayjs(date).format("DD/MM hh:mm");
Yes, definitely. I wasn't sure about which format to use and left it that way so it's easily modifiable.

2022-07-14 11:07 UTC, mwalbeck approved these changes

2022-07-14 12:03 UTC, mwalbeck approved these changes

2022-07-14 12:04 UTC, merged