New UI
MetaProvide/adminly_clients pull request #48
Opened 2022-08-17 11:00 UTC by oliveiraigorm

2022-08-18 13:04 UTC, mwalbeck commented
A few extra things that didn't really fit in the review (coming soon)

![image](https://user-images.githubusercontent.com/19759293/185398932-d817bb85-18d4-43b5-b3d2-59ccd4855969.png)

I would like to have a margin added between the entries here of `0.25rem`

___

![image](https://user-images.githubusercontent.com/19759293/185399130-df4e5ef5-0442-4ce3-ad9d-afe40f2a1956.png)

Is it possible to make this look more like the Figma?

___

![image](https://user-images.githubusercontent.com/19759293/185401204-89c1dc84-2d3e-454f-9263-a168e898514b.png)

I think we should make the timezone select look like the other input fields. It's probably going to take a bit of work to get the height correct, but I think it's going to create a more cohesive visual style.

2022-08-18 13:33 UTC, mwalbeck requested changes

2022-08-18 13:33 UTC, mwalbeck commented on src/components/SessionCard.vue
>  	margin-top: 1.25rem;
This should be changed to `margin: 0.5rem 0 0.25rem;`

2022-08-18 13:45 UTC, oliveiraigorm commented on src/App.vue
> +	display: flex;
The display flex is still important for the create client modal

2022-08-18 13:48 UTC, mwalbeck commented on src/App.vue
> +	display: flex;
Oh sorry, I though I had removed this comment. Yeah, I did notice it was need later one, so you can just ignore it.

2022-08-18 15:52 UTC, mwalbeck commented on src/components/ClientCreation.vue
> +	border-color: var(--adminly-blue) !important;
Yes, definitely! You're welcome to add it to the branch I linked

2022-08-18 15:55 UTC, oliveiraigorm commented on src/components/Table.vue
>  	border: 1 solid var(--adminly-line-color);
not necessary since the tr also has the same rule

2022-08-22 10:29 UTC, mwalbeck requested changes
A few extra things,

Also when clicking on the timezone selector to select a timezone, it changes size. We should have it be a fixed size, so it doesn't affect the layout of the modal.

2022-08-22 10:29 UTC, mwalbeck commented on src/components/ClientsTable.vue
> +	border: 0.5px solid var(--color-border-dark);
border width should be 1px.

2022-08-22 10:29 UTC, mwalbeck commented on src/components/ClientCreation.vue
> +#create-modal .modal-container {
We also need to add the following to this rule:

```
display: flex;
flex-direction: column;
```

2022-08-22 10:29 UTC, mwalbeck commented on src/components/ClientCreation.vue
> +	max-width: 300px;
We should increase the max-width to 320px

2022-08-22 10:29 UTC, mwalbeck commented on src/components/ClientCreation.vue
> +.modal-content {
We should add `align-self: center;` to this rule.

2022-08-22 10:29 UTC, mwalbeck commented on src/components/ClientCreation.vue
> +<style scoped>
We need one more scoped css rule for the client creation modal footer:

```
.modal-footer {
    margin-top: 2rem;
}
```

2022-08-22 10:29 UTC, mwalbeck commented on src/components/ClientModal.vue
> +	max-height: 80% !important;
After a bit more testing I think 80% is a bit too small, so we should set it to 90% instead.

2022-08-22 10:29 UTC, mwalbeck commented on src/components/ClientsTable.vue
Can we get the following css rule added here:

```
.page-selector select {
    margin-right: 1rem;
}
```

2022-08-22 12:49 UTC, oliveiraigorm commented
@mwalbeck About the timezone picker border, I've tried a few things on Friday to change it's height but with no luck. Could you give me some help on it?

2022-08-22 14:59 UTC, mwalbeck commented
> @mwalbeck About the timezone picker border, I've tried a few things on Friday to change it's height but with no luck. Could you give me some help on it?

I'm not quite sure I catch what you're referring to?

___

Though I do have 2 quick things I noticed on the timzone picker. The whole multiselect needs a margin-top of 3px to match the spacing of the other input fields:

![image](https://user-images.githubusercontent.com/19759293/185952992-6f81e6e7-c1ea-4bda-9729-f0f8ce0342a2.png)

Also the `.multiselect__input` itself has a margin-top of 3px that we want to be 0, since it causes the "Type to search timezone" text to not be centered.

2022-08-22 15:04 UTC, oliveiraigorm commented
> I'm not quite sure I catch what you're referring to?

Sorry, I meant making the timezone picker height the same as the other inputs.

2022-08-22 15:14 UTC, mwalbeck commented
But they seemed to be the same height when I checked just before?

2022-08-22 15:24 UTC, oliveiraigorm commented
> But they seemed to be the same height when I checked just before?


It has 36px vs 34px on the normal inputs

![image](https://user-images.githubusercontent.com/29747887/185958505-3d99e764-723f-4762-b3ae-4f167cb3be2e.png)
![image](https://user-images.githubusercontent.com/29747887/185958515-9094e1b3-6644-4f6a-b10d-9d257e456dcf.png)

2022-08-22 23:03 UTC, mwalbeck requested changes
The height of the timezone picker is one of those issues that are quite hard to debug if you don't already know the details of how box-sizing works in CSS. But I've suggested some changes that should touch up the last few things with the selector.

2022-08-23 08:58 UTC, oliveiraigorm commented
Thanks @mwalbeck !

2022-08-23 10:19 UTC, mwalbeck approved these changes
Good job!

2022-08-23 10:20 UTC, merged