Clients table
MetaProvide/adminly_clients pull request #5
Opened 2022-04-26 15:28 UTC by oliveiraigorm

2022-04-26 16:41 UTC, oliveiraigorm commented
The tests are failing in the quotes from Open Sans with either "Open Sans" or 'Open Sans'  `
<style scoped>
table {
	font-family: "Open Sans", sans-serif;`

2022-04-27 10:44 UTC, mwalbeck requested changes
There is an issue with descriptions not showing up, but that is caused by bug in the jsonSerialize function. I've created a fix here: https://github.com/MetaProvide/adminly_clients/pull/6

2022-04-27 10:44 UTC, mwalbeck commented on lib/Db/ClientMapper.php
> +	public function create(Client $client) {
Why has this returned?

2022-04-27 10:44 UTC, mwalbeck commented on src/components/Table.vue
> +				<tr v-for="client in clients" :key="client.username">
Are the keys needed here?

2022-04-27 11:54 UTC, oliveiraigorm commented on lib/Db/ClientMapper.php
> +	public function create(Client $client) {
was from a merge that I did from main and forgot that it wasn't necessary anymore

2022-04-27 13:26 UTC, oliveiraigorm commented on src/components/Table.vue
> +				<tr v-for="client in clients" :key="client.username">
Vue complains when there's a v-for without a key

2022-04-27 15:34 UTC, mwalbeck approved these changes
Just to unblock so Henry can take over.

2022-04-27 15:34 UTC, frozenbanana commented on src/components/ClientCreation.vue
> +.modal__content {
not sure about this naming convention. we have not used it before. Perhaps we should decide on one asap. 

This style looks like BEM and the rest of your classes are not following it. `.model-content`` makes more sense for now.

2022-04-27 15:38 UTC, frozenbanana commented on src/components/Table.vue
> +			columns: ["name", "email", "description"],
I think this can be a computed value instead of hardcoded state.

```
computed() {
     columns() {
         return Object.keys(this.clients);
     }
}```

try it out.

2022-04-27 15:38 UTC, frozenbanana requested changes
See comments above.

2022-04-27 16:10 UTC, oliveiraigorm commented on src/components/Table.vue
> +			columns: ["name", "email", "description"],
tried it an it adds more problems since we don't want to display all the keys from a client like id, providerId in the table, needing more code to filter it out, so I don't think it's worth it.

2022-04-28 06:46 UTC, frozenbanana approved these changes

2022-04-28 11:37 UTC, merged