Limit of 2 letters for the avatars
MetaProvide/adminly_clients pull request #62
Opened 2022-09-29 11:36 UTC by oliveiraigorm

### Changes

Created a function that gets only the first and last name of a client to use as a parameter for the avatar component

### Testing

Create a client with 2 or more surnames

### Screenshot

![image](https://user-images.githubusercontent.com/29747887/193021034-a0e24e4a-47bb-4ca6-b6ad-6384670c467b.png)

2022-10-04 11:56 UTC, mwalbeck commented
3 letters are still being used in the clients details pop-up

![image](https://user-images.githubusercontent.com/19759293/193813373-a54afcde-c38b-496f-b3f2-d4520b2137ab.png)

2022-10-04 11:56 UTC, mwalbeck requested changes
See above comment

2022-10-05 14:45 UTC, frozenbanana requested changes

2022-10-05 14:45 UTC, frozenbanana commented on src/components/ClientModal.vue
> +			fullName = fullName.split(" ");
mutating the argument like that makes me nervous. Strings are passed by reference (since it is an object). It is most proberbly fine here but I think we should avoid mutating arguments if it not needed.

`const fullNameArray = fullname.split(" ")` would work fine here.

2022-10-06 12:56 UTC, mwalbeck commented on src/components/ClientModal.vue
> +			fullName = fullName.split(" ");
I agree, this could be the cause of a potential bug in the future, so might as well change it now

2022-10-10 11:10 UTC, mwalbeck approved these changes

2022-10-10 11:11 UTC, merged