Card/2629/1
MetaProvide/adminly_clients pull request #66
Opened 2022-10-27 16:09 UTC by oliveiraigorm

### Changes

Adds a new button to send email to clients
Removes transitions from action buttons

### Testing

Click the button and your email client should open with a new email page with the client's address as the recipient

### Screenshot

![image](https://user-images.githubusercontent.com/29747887/198342012-6c5f8db7-f97d-4f41-b5f3-9c63c0fa6beb.png)

2022-10-28 13:41 UTC, mwalbeck requested changes

2022-10-28 13:41 UTC, mwalbeck commented on src/components/Table.vue
> +	padding: 6px 16px;
The padding and the width do not seem to do anything. The padding is overwritten by a padding-inline rule that is applied to `.svg`

2022-10-28 14:38 UTC, oliveiraigorm commented
@mwalbeck I accidentally ended up solving the following card (or part of it):
https://space.metaprovide.org/apps/deck/#/board/49/card/2535

2022-11-01 17:56 UTC, mwalbeck approved these changes

2022-11-01 17:56 UTC, merged