Overview cards
MetaProvide/adminly_clients pull request #8
Opened 2022-05-05 04:57 UTC by MartinPirate

2022-05-06 14:49 UTC, oliveiraigorm commented
I've tested it and I couldn't get all 4 cards in a single row. Also the cards are not aligned with the table 
![image](https://user-images.githubusercontent.com/29747887/167157022-61dbbed9-6d0a-4623-ac81-010fde36da8d.png)

2022-05-08 07:06 UTC, frozenbanana commented on src/components/CardOverview.vue
> +												</svg>-->
Remove if not using

2022-05-08 07:07 UTC, frozenbanana commented on src/components/ClientModal.vue
> +}
avoid using `!important`.

If you must use it please motive why.

2022-05-08 07:09 UTC, frozenbanana commented on src/components/ClientModal.vue
> +
I am noting a lot of these utility classes lately.

I think it makes sense to create our own importable CSS file with all of these util classes. God forbid we might use tailwind css. It is ok for now but we should talk about this next week.

2022-05-08 07:11 UTC, frozenbanana requested changes
I think we should prioritize having a row of 4 cards. I would increase the width of the table slightly and decrease the card width slightly to make that happen.

Small comment regarding `!important` otherwise good.

2022-05-08 07:13 UTC, MartinPirate commented on src/components/ClientModal.vue
> +
I will make the necessary updates in a few

2022-05-09 17:06 UTC, oliveiraigorm commented
@MartinPirate I believe you based your branch on the clientView branch. That can create some confusion and conflicts so in the future it's better to base it on the main branch.

2022-05-09 17:14 UTC, MartinPirate commented
@oliveiraigorm  yeah I did base my work on the clientView branch, the main page didn't have the table view  which i needed for  further tests, will watch out next time

2022-05-09 17:58 UTC, MartinPirate commented on src/components/ClientModal.vue
> +}
this was not me  @frozenbanana

2022-05-09 17:59 UTC, MartinPirate commented on src/components/ClientModal.vue
> +
I based my changes to @oliveiraigorm  branch which was my bad, wanted to use the table view  for determining the total cards length

2022-05-09 18:00 UTC, MartinPirate commented on src/components/CardOverview.vue
> +												</svg>-->
noted

2022-05-11 11:55 UTC, frozenbanana commented on src/components/CardOverview.vue
> +	/*	margin: 16px;*/
Remove if not using

2022-05-11 11:56 UTC, frozenbanana commented on src/components/CardOverview.vue
> +		},
Not sure when we would like to have `showData`  to be false. 

Consider removing it.

2022-05-11 11:58 UTC, MartinPirate commented on src/components/CardOverview.vue
> +		},
i use it to set the forth card to empty 
will be removed once they decide what will be added on the  card

2022-05-18 11:17 UTC, mwalbeck commented on src/components/CardOverview.vue
> +												</svg>-->
@MartinPirate ping

2022-05-18 11:17 UTC, mwalbeck commented
I've tried to give it a spin, but nothing is showing up for me, is there something I'm missing? @MetaProvide/adminly

2022-05-18 11:34 UTC, oliveiraigorm commented
> I've tried to give it a spin, but nothing is showing up for me, is there something I'm missing? @MetaProvide/adminly

It was working fine before but I believe the component was removed by mistake on this commit https://github.com/MetaProvide/adminly_clients/pull/8/commits/64bd5c37a3ac7bd75ae19af66ed9a061dd356f69

@MartinPirate

2022-05-18 12:52 UTC, MartinPirate commented
@mwalbeck  please test now

2022-05-18 18:55 UTC, mwalbeck requested changes

2022-05-18 18:55 UTC, mwalbeck commented on src/components/CardOverview.vue
> +	box-shadow: 0px 0px 10.6566px rgba(0, 0, 0, 0.15);
Whenever something is 0, just use 0 with no units. Also, for simplicity lets try and keep the numbers round, so use 11 for the box-shadow.

2022-05-18 18:55 UTC, mwalbeck commented on src/components/CardOverview.vue
> +}
If you add a `margin-right: 2rem` then we get some nice spacing between the boxes and still rely on flexbox for the actual sizing, so the elements are more dynamic.

2022-05-18 18:55 UTC, mwalbeck commented on src/components/CardOverview.vue
> +
Lastly we should add a new rule
```
.card:last-of-type {
	margin-right: 0;
}
```
That way we get the intended look.

2022-05-18 18:55 UTC, mwalbeck commented on src/components/CardOverview.vue
> +	padding: 18px;
It's generally preferable to use relative units for padding, so here `1rem` will do.

2022-05-18 18:55 UTC, mwalbeck commented on src/components/CardOverview.vue
> +	font-size: 12.7879px;
For font-size we also want to use relative units instead, so here we can use `0.8rem`

2022-05-18 18:55 UTC, mwalbeck commented on src/components/CardOverview.vue
> +	font-size: 31.9697px;
Use `2rem` instead.

2022-05-18 18:55 UTC, mwalbeck commented on src/components/CardOverview.vue
> +	line-height: 40px;
Use `2.5rem` instead

2022-05-18 18:55 UTC, mwalbeck commented on src/components/CardOverview.vue
> +	height: 0px;
Unneeded

2022-05-18 18:55 UTC, mwalbeck commented on src/components/CardOverview.vue
> +.card-data span svg {
Not really needed

2022-05-18 18:55 UTC, mwalbeck commented on src/components/CardOverview.vue
> +.card-data span {
The only rules needed here are:
```
font-weight: 400;
font-size: 0.8rem;
color: #8e8e8e;
```

2022-05-18 18:55 UTC, mwalbeck commented on src/components/CardOverview.vue
> +				<div class="card-history">
I would replace this card-history section with:
```
<div class="card-history">
	<div class="card-history-entry history-yesterday">
		<span>Yesterday</span>
		<span>
			{{ yesterdayCount }} ({{
				yesterdayPercentageChange
			}}
			%)
		</span>
	</div>
	<div class="card-history-entry history-last-week">
		<span>Last week</span>
		<span>
			{{ lastWeekCount }} (
			{{ lastWeekPercentageChange }} %)
		</span>
	</div>
</div>
```
That accompanied by the CSS suggestions make the setup simpler and easier to maintain.

2022-05-18 18:55 UTC, mwalbeck commented on src/components/CardOverview.vue
> +.card-history {
Replace this rule and the rest related to the card-history with the following:

```
.card-history {
	display: flex;
	flex-direction: column;
	font-size: 0.8rem;
}

.card-history .history {
	display: flex;
	justify-content: space-between;
}
```

2022-05-19 10:55 UTC, mwalbeck commented on src/components/CardOverview.vue
> +	height: 1.1rem;
Is there a specific reason why you kept the height parameter?

2022-05-19 10:55 UTC, mwalbeck commented on src/components/CardOverview.vue
>  	font-style: normal;
This one can also be removed

2022-05-19 10:55 UTC, mwalbeck commented on src/components/CardOverview.vue
>  	font-weight: 400;
As well as this one

2022-05-19 15:08 UTC, mwalbeck commented on src/components/CardOverview.vue
>  	font-style: normal;
ping @MartinPirate

2022-05-19 15:08 UTC, mwalbeck commented on src/components/CardOverview.vue
>  	font-weight: 400;
ping @MartinPirate

2022-05-20 10:43 UTC, mwalbeck submitted a review, later dismissed

2022-05-20 10:47 UTC, mwalbeck approved these changes

2022-05-20 10:48 UTC, merged