Client edit
MetaProvide/adminly_clients pull request #9
Opened 2022-05-05 11:59 UTC by oliveiraigorm

![image](https://user-images.githubusercontent.com/29747887/166918665-f4d472f1-e5bd-45e6-bcd8-3292dbeb1139.png)
![image](https://user-images.githubusercontent.com/29747887/166918699-7ebd5752-caea-4447-86fd-1941b5987df0.png)

2022-05-08 07:04 UTC, frozenbanana requested changes
Small change on controller method otherwise good.

2022-05-08 07:04 UTC, frozenbanana commented on lib/Controller/PageController.php
> +			return "Success";
Use the pattern found in the note tutorial app.
```
	public function update($id, $title, $content, $userId) {
		try {
			$note = $this->mapper->find($id, $userId);
			$note->setTitle($title);
			$note->setContent($content);
			return $this->mapper->update($note);
		} catch (Exception $e) {
			$this->handleException($e);
		}
	}
```

https://github.com/nextcloud/app-tutorial/blob/master/lib/Service/NoteService.php

2022-05-09 10:52 UTC, oliveiraigorm commented on lib/Controller/PageController.php
> +			return "Success";
done

2022-05-09 11:09 UTC, frozenbanana submitted a review, later dismissed
👏

2022-05-10 10:27 UTC, mwalbeck approved these changes

2022-05-10 10:27 UTC, merged